# To automatically enable dependencies for Github Pages deployments:
# 1. Make sure every PRIOR line consists of '#[github-pages]'
# 2. Then run `convert-to-gh-pages.sh`

### WEBSITE VARIABLES ###
name: "Sustainability Dashboard"
repo_url: "https://github.com/corsa-center/dashboard"
repo_branch: "dev"
# tree path varies based on github/gitlab repo, gitlab should be "-/tree"
repo_tree_path: "tree"
repo_blob_path: "blob"
lab_name: "CASS"

### SEO ###

title: Sustainability Dashboard
tagline: A hub for showcasing the sustainability of scientific open-source software
description: "Get the latest news and metadata about scientific software"
url: "https://cass-community.github.io/dashboard/"
author: "CORSA Open Source Software <info@corsa.center>"
twitter:
  username: cass

# google_site_verification: 477TVoInt3HiUgSl_hU4rb5_JrgNMKK5Rl-KPMUClpQ

# Google Analytics ID
#google_analytics:
#  tracking_id: UA-75179431-1

### GitHub Metadata -- https://github.com/jekyll/github-metadata ###
#[github-pages]
repository: corsa-center/dashboard

#[github-pages]
remote_theme: ORNL/Jekyll-ORNL-Theme@main

### JEKYLL DEFAULTS ###

# NOTE: the website needs to be able to work with the next line both commented AND uncommented
baseurl: "/dashboard"

# supported Github plugins are available at https://pages.github.com/versions/
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  #[github-pages]
  - jekyll-remote-theme

kramdown:
  auto_ids: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/news/:year/:month/:day/:title/"
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/logo/cass-small-logo.png

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - build
  - public
  - CNAME
  - CONTRIBUTING.md
  - convert-to-gh-pages.sh
  - Makefile
  - README.md
  - setup.cfg
  - worker.Dockerfile

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
