name: Run data update

on:
   workflow_dispatch:
   schedule:
     - cron: "0 2 * * *"  # Run daily at 2:00 AM UTC
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
        with:
          ref: ${{ vars.UPDATE_BRANCH }}
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r _explore/scripts/requirements.txt
      - name: Setup Spack # Spack is not yet pip installable, so we must install via the actions
        uses: spack/setup-spack@v2
        with:
          ref: develop-2025-04-13
          buildcache: false
          color: false
          path: spack
      - name: Run update script
        run:
          ./_explore/scripts/UPDATE.sh
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for changes
        id: check-changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes detected"
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "has-changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit changes
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -m "Ran collection scripts [AUTO-GENERATED]"
          git push
      - name: Merge changes into main branch
        if: steps.check-changes.outputs.has-changes == 'true'
        run: |
          git fetch origin "${DEPLOY_BRANCH}:${DEPLOY_BRANCH}"
          git checkout "${DEPLOY_BRANCH}"
          git branch --set-upstream-to=origin/"${DEPLOY_BRANCH}" "${DEPLOY_BRANCH}"
          git pull
          git merge "${UPDATE_BRANCH}"
          git push --set-upstream origin "${DEPLOY_BRANCH}"
        env:
          DEPLOY_BRANCH: ${{ vars.DEPLOY_BRANCH }}
          UPDATE_BRANCH: ${{ vars.UPDATE_BRANCH }}
